/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

#include<stdio.h>
int main()
{
	printf("jay shree krishna\n");
	printf("jay swaminarayan\n");
	for(;;);
}
