/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

#include<stdint.h>

int main(void)
{
	// calculate peripheral register using manual and their offset
	uint32_t *pClkCtrlReg =   (uint32_t*)0x40023830;
	uint32_t *pPortDModeReg = (uint32_t*)0x40020C00;
	uint32_t *pPortDOutReg =  (uint32_t*)0x40020C14;

    // 1. Enable the clock for gpioD peripheral in AHB1ENR
	 // set using bitwise | operation to 3rd bit position
	*pClkCtrlReg |= ( 1 << 3);

	// 2. Configure the mode of I/O pin as output
	 //a. clear a 24 & 25 bit position
	*pPortDModeReg &= ~( 3 << 24); //(green)
	*pPortDModeReg &= ~( 3 << 26); //(orange)
	*pPortDModeReg &= ~( 3 << 28); //(red)
	*pPortDModeReg &= ~( 3 << 30); //(blue)

	 //b. make 24 bit position 1 (Set)
	*pPortDModeReg |= ( 1 << 24); //(green)
	*pPortDModeReg |= ( 1 << 26); //(orange)
	*pPortDModeReg |= ( 1 << 28); //(red)
	*pPortDModeReg |= ( 1 << 30); //(blue)

	// 3. set 12 bit of output data register to make i/o pin 12 as High
	*pPortDOutReg |= ( 1 << 12);  //(green)
	*pPortDOutReg |= ( 1 << 13);  //(orange)
	*pPortDOutReg |= ( 1 << 14);  //(red)
	*pPortDOutReg |= ( 1 << 15);  //(blue)

    while(1);

    /////// check all SFR register  /////////
}
