/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

#include<stdio.h>
extern void initialise_monitor_handles(void);
int main()
{
	initialise_monitor_handles();
	printf("Nilesh Asodariya\n");
	printf("Mayur Asodariya\n");
	for(;;);
}
