/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


#include<stdio.h>
#include<stdint.h>

#include "pinread.h"

	/*  uint32_t  volatile *const pClkCtrlReg =   (uint32_t*)0x40023830;
		uint32_t  volatile *const pPortDModeReg = (uint32_t*)0x40020C00;
		uint32_t  volatile *const pPortDOutReg =  (uint32_t*)0x40020C14;

		uint32_t volatile *const pPortAModeReg =     (uint32_t*)0x40020000;
		uint32_t const volatile *const pPortAInReg = (uint32_t*)0x40020010;   */


int main(void)

{
		RCC_AHB1ENR_t volatile *const pClkCtrlReg   = (RCC_AHB1ENR_t*) 0x40023830;
		GPIOx_MODE_t  volatile *const pPortDModeReg = (GPIOx_MODE_t*) 0x40020C00;
		GPIOx_ODR_t   volatile *const pPortDOutReg  = (GPIOx_ODR_t*) 0x40020C14;

		GPIOx_MODE_t  volatile *const pPortAModeReg = (GPIOx_MODE_t*) 0x40020000;
		GPIOx_IDR_t   volatile *const pPortAInReg  = (GPIOx_ODR_t*) 0x40020010;

	    //enable the clock for GPOID , GPIOA peripherals in the AHB1ENR
	    pClkCtrlReg->gpiod_en = 1;
	    pClkCtrlReg->gpioa_en = 1;

	    //configuring PD12 as output
		pPortDModeReg->pin_12 = 1; //(green)
		pPortDModeReg->pin_13 = 1; //(orange)

		//Configure PA0 & PA1 as input mode (GPIOA MODE REGISTER)
		pPortAModeReg->pin_0 = 0;
		pPortAModeReg->pin_1 = 0;

		while(1)
			{


				//read the pin status of the pin PA1 (GPIOA INPUT DATA REGISTER)
			GPIOx_IDR_t  pinStatus0 = (pPortAInReg->pin_0 & 0x1); //zero out all other bits except bit 0



				if(pinStatus0) {
					//turn on the LED
					pPortDOutReg->pin_12  = 1; //(green)
					pPortDOutReg->pin_13  = 1; //(orange)

				}else{
					//turn off the LED

					pPortDOutReg->pin_12  = 0; //(green)
					pPortDOutReg->pin_13  = 0; //(orange)

				}

			}


	for(;;);
}
