/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

#include<stdint.h>

int main(void)
{
	uint32_t *pClkCtrlReg =   (uint32_t*)0x40023830;
	uint32_t *pPortDModeReg = (uint32_t*)0x40020C00;
	uint32_t *pPortDOutReg =  (uint32_t*)0x40020C14;

	//1. enable the clock for GPOID peripheral in the AHB1ENR (SET the 3rd bit position)
	*pClkCtrlReg |= ( 1 << 3);

	//2. configure the mode of the IO pin as output
	//a. clear the 24th and 25th bit positions (CLEAR)
	*pPortDModeReg &= ~( 3 << 24); //(green)
	*pPortDModeReg &= ~( 3 << 26); //(orange)
	*pPortDModeReg &= ~( 3 << 28); //(red)
	*pPortDModeReg &= ~( 3 << 30); //(blue)

	//b. make 24th bit position as 1 (SET)
	*pPortDModeReg |= ( 1 << 24); //(green)
	*pPortDModeReg |= ( 1 << 26); //(orange)
	*pPortDModeReg |= ( 1 << 28); //(red)
	*pPortDModeReg |= ( 1 << 30); //(blue)

	while(1)
	{
		// toggling in round

		*pPortDOutReg |= ( 1 << 14); //(red)
		for(uint32_t i=0 ; i < 300000 ; i++ );
		*pPortDOutReg &= ~( 1 << 14); //(red)
		for(uint32_t i=0 ; i < 300000 ; i++ );

		*pPortDOutReg |= ( 1 << 15); //(blue)
		for(uint32_t i=0 ; i < 300000 ; i++ );
		*pPortDOutReg &= ~( 1 << 15); //(blue)
		for(uint32_t i=0 ; i < 300000 ; i++ );

		*pPortDOutReg |= ( 1 << 12); //(green)
		for(uint32_t i=0 ; i < 300000 ; i++ );
		*pPortDOutReg &= ~( 1 << 12); //(green)
		for(uint32_t i=0 ; i < 300000 ; i++ );

		*pPortDOutReg |= ( 1 << 13); //(orange)
		for(uint32_t i=0 ; i < 300000 ; i++ );
		*pPortDOutReg &= ~( 1 << 13); //(orange)
		for(uint32_t i=0 ; i < 300000 ; i++ );

	}

	//// you should make the processor busy in a software loop doing nothing
	//// This method is not an accurate method to obtain the desired time delay /////

	// the accurate method is hardware peripherals such as *timers*


}
